import 'dart:convert';

import 'package:bpp_shop/bpp/google_map/Google_map_screen.dart';
import 'package:bpp_shop/bpp/google_map/getdist_api.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class Address extends StatefulWidget {
  String? districtName;


  Address({this.districtName});

  @override
  State<Address> createState() => _AddressState();
}

var district = '';

class _AddressState extends State<Address> {

  Future getApiData() async{
    String url ="https://bppshops.com/api/district/ajax/3";
    var result = await http.get(Uri.parse(url));
    // print(result.body);
    apiList = jsonDecode(result.body)
        .map((item) =>Autogenerated .fromJson(item))
        .toList()
        .cast<Autogenerated>();

    setState(() {

    });
  }

  List<Autogenerated>? apiList;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
     getApiData();
  }

  // String? friendval;
  //
  // List _friendName = ['Dhaka', 'Dhaka City'];

  TextEditingController _districtController = TextEditingController();
  //var district='';
  @override
  Widget build(BuildContext context) {
    // if(widget.districtName!=null){
    //   _districtController=widget.districtName.toString() as TextEditingController;
    // }
    return Scaffold(
      appBar: AppBar(
        elevation: 5,
        backgroundColor: Colors.white,
        leading: IconButton(
          onPressed: () {
            Navigator.pop(context);
          },
          icon: Icon(Icons.arrow_back),
          color: Colors.black,
        ),
        title: Text(
          'Confirm Delivery Address',
          style: TextStyle(color: Colors.black),
        ),
      ),
      body: SingleChildScrollView(
        child: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          margin: EdgeInsets.all(15),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                height: 10,
              ),
              Text(
                "Street Address",
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 15,
                ),
              ),
              TextFormField(
                maxLines: 3,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
//hintText: 'Full Name',
                ),
              ),
              SizedBox(height: 10,),
              Text(
                "736 New Gulbadan Super Market,5 Moulvi Bazar,Dhaka",
                style: TextStyle(
                  color: Colors.orangeAccent,
                  fontWeight: FontWeight.bold,
                ),
              ),


              SizedBox(height: 10,),
              Text(
                "District Select",
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 15,
                ),
              ),

                Container(
                  margin: EdgeInsets.symmetric(vertical: 10),
                  height: 40,
                  width: MediaQuery.of(context).size.width * .9,
                  child: TextFormField(
                    // onTap: ()  {
                    //   Navigator().of
                    //   //final  result = await showSearch(context: context, delegate: districtSearchList());
                    //
                    //   setState(() {
                    //    // district= result.toString();
                    //   });
                    //
                    //
                    // },

                    onTap: () {
                      // Navigator.of(context)
                      //     .push(MaterialPageRoute(builder: (context) => MyApi()));

                      
                      showDialog(context: context, builder: (BuildContext context){
                          getApiData();
                        return Scaffold(

                          body: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              if(apiList !=null)
                                getList(),
                              ElevatedButton(onPressed: (){
                                getApiData();
                              }, child: Text("Get Data"))
                            ],


                          ),
                        );
                      });
                    },

                    controller: _districtController,
                    decoration: InputDecoration(
                      hintText:(district),
                      border: OutlineInputBorder(),
//hintText: 'Full Name',
                    ),
                  ),
              ),
              SizedBox(height: 10,),
              Text(
                "Area/ Thana",
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 15,
                ),
              ),
              Container(
                margin: EdgeInsets.symmetric(vertical: 10),
                height: 40,
                width: MediaQuery.of(context).size.width * .9,
                child: TextFormField(
                  decoration: InputDecoration(
                    hintText:('Select'),
                    border: OutlineInputBorder(),
//hintText: 'Full Name',
                  ),
                ),
              ),
              SizedBox(
                height: 20,
              ),

              Text(
                "Phone Number",
                style: TextStyle(
                  color: Colors.grey,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Container(
                margin: EdgeInsets.symmetric(vertical: 10),
                height: 40,
                width: MediaQuery
                    .of(context)
                    .size
                    .width * .9,
                child: TextFormField(
                  decoration: InputDecoration(
                    hintText: '+880145*******',
                    border: OutlineInputBorder(),
//hintText: 'Full Name',
                  ),
                ),
              ),
              Container(
                  margin: EdgeInsets.only(top: 20),
                  width: MediaQuery
                      .of(context)
                      .size
                      .width,
                  height: 120,
                  decoration: BoxDecoration(
                    border: Border.all(
                      color: Color(0xffF5DCD0),
                      width: 1,
                    ), //Border.all
                    borderRadius: BorderRadius.circular(15),
                    boxShadow: [],
                  ),
                  child: GoogleMapScreen()),
              SizedBox(
                height: 20,
              ),
              ElevatedButton(
                child: const Text(
                  'Save Address',
                  style: TextStyle(fontSize: 18),
                ),
                onPressed: () {
                  // district = showSearch(context: context,
                  //     delegate: ProductSearchDelegate()) as String;
                },
                style: ElevatedButton.styleFrom(
                  shape: new RoundedRectangleBorder(
                    borderRadius: new BorderRadius.circular(10),
                  ),
                  maximumSize: Size(400, 100),
                  minimumSize: Size(360, 50),
                  primary: Colors.orange,
                  //padding: EdgeInsets.symmetric(horizontal: 90,vertical: 15)
                ),
              ),
            ],
          ),

        ),
      ),

    );

  }

  Widget getList(){
    return Expanded(
      child: ListView.builder(
          itemCount: apiList!.length,
          itemBuilder: (BuildContext context ,int index){
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                GestureDetector(
                  onTap: (){
                    setState(() {
                      district= apiList![index].name.toString();
                    });
                    Navigator.pop(context);
                    //Navigator.of(context).push(MaterialPageRoute(builder: (context)=>Address(districtName: apiList![index].name,)));
                  },
                  child: Card(
                      elevation: 5,
                      child:Container(
                        width: double.infinity,
                        padding: EdgeInsets.fromLTRB(5,10, 0, 10),
                        child:Text("${apiList![index].name}"),
                      )
                  ),
                ),

              ],
            );
          }),
    );

  }
  }

